components:
  zookeeper: true
  oxia: false
  bookkeeper: false
  autorecovery: false
  broker: false
  functions: false
  proxy: false
  toolset: false
  pulsar_manager: false

tls:
  enabled: true
  zookeeper:
    enabled: true

certs:
  internal_issuer:
    # Create a self-signed issuer
    enabled: true
    type: selfsigning
  issuers:
    # Set CA issuer name and secret name so we can reuse them for the other pulsar clusters
    ca:
      name: pulsar-ca-issuer
      secretName: pulsar-ca-issuer-tls
