{{- if .Values.auth.authentication.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kubectl
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"

{{- end }}