#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.bookkeeper }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.bookkeeper.component }}
data:
  # common config
  {{- include "pulsar.bookkeeper.config.common" . | nindent 2 }}
  {{- if .Values.components.autorecovery }}
  # disable auto recovery on bookies since we will start AutoRecovery in separated pods
  autoRecoveryDaemonEnabled: "false"
  {{- end }}
  # Do not retain journal files as it increase the disk utilization
  journalMaxBackups: "0"
  {{- if .Values.bookkeeper.volumes.journal.useMultiVolumes }}
  {{- $journalDirs := list -}}
  {{ range .Values.bookkeeper.volumes.journal.multiVolumes }}
  {{- $journalDirs = append $journalDirs .mountPath -}}
  {{- end }}
  journalDirectories: {{ $journalDirs | join "," | quote }}
  PULSAR_PREFIX_journalDirectories: {{ $journalDirs | join "," | quote }}
  {{- else }}
  journalDirectories: "/pulsar/data/bookkeeper/journal"
  PULSAR_PREFIX_journalDirectories: "/pulsar/data/bookkeeper/journal"
  {{- end }}
  {{- if .Values.bookkeeper.volumes.ledgers.useMultiVolumes }}
  {{- $ledgerDirs := list -}}
  {{ range .Values.bookkeeper.volumes.ledgers.multiVolumes }}
  {{- $ledgerDirs = append $ledgerDirs .mountPath -}}
  {{- end }}
  ledgerDirectories: {{ $ledgerDirs | join "," | quote }}
  {{- else }}
  ledgerDirectories: "/pulsar/data/bookkeeper/ledgers"
  {{- end }}
  {{- if .Values.functions.useBookieAsStateStore }}
  # Stateful function config
  extraServerComponents: "org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent"
  {{- end }}
  # TLS config
  {{- include "pulsar.bookkeeper.config.tls" . | nindent 2 }}
  {{- if .Values.bookkeeper.useRocksDBConfigInConfigData }}
  # Set RocksDB default format version to 5
  # RocksDB format_version 5 has been supported since RocksDB 6.6 . It's required for certain performance optimizations.
  PULSAR_PREFIX_dbStorage_rocksDB_format_version: "5"
  # Specify non-existing files to avoid Bookkeeper from loading RocksDB config from existing files
  PULSAR_PREFIX_defaultRocksdbConf: "conf/non_existing_default_rocksdb.conf"
  PULSAR_PREFIX_entryLocationRocksdbConf: "conf/non_existing_entry_location_rocksdb.conf"
  PULSAR_PREFIX_ledgerMetadataRocksdbConf: "conf/non_existing_ledger_metadata_rocksdb.conf"
  {{- else }}
  # Specify existing files to load RocksDB config from existing files
  PULSAR_PREFIX_defaultRocksdbConf: "conf/default_rocksdb.conf"
  PULSAR_PREFIX_entryLocationRocksdbConf: "conf/entry_location_rocksdb.conf"
  PULSAR_PREFIX_ledgerMetadataRocksdbConf: "conf/ledger_metadata_rocksdb.conf"
  {{- end }}
{{ toYaml .Values.bookkeeper.configData | indent 2 }}
{{- end }}