#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.pulsar_manager.ingress.enabled }}
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.Version }}
apiVersion: extensions/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_manager.component }}
  annotations:
{{- with .Values.pulsar_manager.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
  namespace: {{ template "pulsar.namespace" . }}
spec:
{{- if .Values.pulsar_manager.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.pulsar_manager.ingress.hostname }}
      {{- with .Values.pulsar_manager.ingress.tls.secretName }}
      secretName: {{ . }}
      {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.pulsar_manager.ingress.path }}
            {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.Version }}
            backend:
              serviceName: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
              servicePort: {{ .Values.pulsar_manager.service.targetPort }}
            {{- else }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
                port:
                  number: {{ .Values.pulsar_manager.service.targetPort }}
            {{- end }}
      {{- if .Values.pulsar_manager.ingress.hostname }}
      host: {{ .Values.pulsar_manager.ingress.hostname }}
      {{- end }}
{{- end }}
